--- #YAML:1.0
name: Algorithm-RabinKarp
version: 0.36
author:
  - Norman Nunley <nnunley@gmail.com>
abstract: An implementation of the Rabin-Karp rolling hash algorithm
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
